server:
  port: 8012
spring:
  application:
    name: collect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 20
      maximum-pool-size: 50
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启二级缓存
    map-underscore-to-camel-case: true
    # 当映射为空, 仍显示
    call-setters-on-nulls: true
  type-aliases-package: com.yozosoft.app.collect.*
seata:
  service:
    grouplist:
      defalut: 127.0.0.1:8091