server:
  port: 7000
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway
  config:
    import: nacos:bootstrap.yml
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
logging:
  config: classpath:logback-spring.xml
